# Generated by Django 4.2.4 on 2023-11-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_applied_alter_order_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applied',
        ),
    ]
