# Generated by Django 4.2.4 on 2023-11-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
