# Generated by Django 4.2.4 on 2024-05-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
