# Generated by Django 4.2.4 on 2024-05-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_order_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_carty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
