# Generated by Django 4.2.4 on 2024-05-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_remove_product_old_carty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='old_cart',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
