# Generated by Django 4.2.4 on 2024-05-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_alter_order_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='old_cart',
        ),
    ]
