# Generated by Django 4.2.4 on 2024-05-07 17:38

from django.db import migrations, models
import django.utils.timezone
import store_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0019_orderitem_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Dispatch'), (3, 'On the way'), (4, 'Arrived in City'), (5, 'Delivered')], default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='userDetail',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100, verbose_name=store_app.models.Order),
            preserve_default=False,
        ),
    ]
