# Generated by Django 4.2.4 on 2024-05-09 08:09

import datetime
from django.db import migrations, models
import store_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0020_orderitem_status_orderitem_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, verbose_name=store_app.models.Order)),
                ('reviewMessage', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
